name: Build & Release Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Bump version automatically
        run: |
          npm version patch -m "auto release %s"

      - name: Push changes
        run: git push origin main --follow-tags

      - name: Build & Publish
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
